### ISSUE TITLE
In-Memory BackEnd

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#645]
I think an in-memory backend would be a good addition for testing smaller simulations. Specifically, I'm looking to test full simulations that use some of the Cycamore modules, and having to add another layer of database reading is non-ideal. 

The process would be significantly streamlined If I could instead run the simulation and then query an in-memory BackEnd afterward.

I think the largest task for this issue would be determining the table-like data structure layout. I've been told that this shouldn't take that long, though (~30 min). 

Can I get a general opinion on the suggestion @rwcarlsen, @scopatz ?

**Comment by rwcarlsen** [comment]
sqlite has a built-in in-memory backend functionality accessible by just passing `:memory:` as the db file path.  I think this is good enough.

**Comment by scopatz** [comment]
I am reopening because HDF5's in-memory capabilities have not been hooked up yet.

**Comment by rwcarlsen** [comment]
The original issue was so we could test that things that weren't the db writing worked - e.g. check that archetypes and resource exchange were operating properly.  The original reasons for the issue have been more than addressed.  If there are any needs that are explicitly require hdf5 memory db support, could you please describe them?

**Comment by rwcarlsen** [comment]
Specifically, we wanted to be able to run small, mock simulations to test things out - this is completely addressed by generalized backend querying in addition to all the mock simulation stuff we just merged in.

**Comment by scopatz** [comment]
We still do not have a way for users to specify that they want the backends to be in-memory when they run a simulation.  This interface should be applicable to any backend (assuming the backend supports it).

**Comment by rwcarlsen** [comment]
When would they need in-memory databases for something other than testing?  For testing, sqlite more than serves needs.  Most hdf5's benefits for cyclus are not helpful for in-memory.  Sqlite in-mem is at least as fast and hdf5's, and large dataset handling is not so important if it has to fit in memory anyway.  All present use-case based needs have been addressed.  If there aren't any specific needs that need to be addressed, then I don't think that this is high enough priority to be bugging us in the issues.  So I would prefer it closed or addressed.

**Comment by scopatz** [comment]
I can see a use case where people just want to compute a value in situ, report it to the screen, and then move on.  This is most helpful in optimization.  There is no reason to not give this feature to users.  Unfortunately, I am all tied up for the moment. I don't see the harm in letting this sit open until it becomes someone's need.

**Comment by rwcarlsen** [comment]
Why isn't that purpose served by sqlite in-memory?

**Comment by scopatz** [comment]
User's should have the choice of what backend they use.

**Comment by gidden** [comment]
moved to 1.4
